[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "14.x"

[context.production.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
