[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.15.0"

[context.production.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
